name: Build Native Image and Push to GHCR

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
          
      - name: Access-Rights for maven execution Blog-Backend
        run: cd blog-backend && chmod +x mvnw && cd ..

      - name: Access-Rights for maven execution Validator-messager
        run: cd validator-messager && chmod +x mvnw && cd ..

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Login with a Repository Secret with a Token with Access to GitHub Packages
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and Push Native Image over Maven-Wrapper Blog-Backend
      - name: Build with Maven Blog-Backend
        run: cd blog-backend && ./mvnw verify && cd .. && docker push ghcr.io/ferberj/kafka-blog-backend

      # Build and Push Native Image over Maven-Wrapper Validator-messager
      - name: Build with Maven Validator-messager
        run: cd validator-messager && ./mvnw verify && cd .. && docker push ghcr.io/ferberj/kafka-validator
